#
#    ____ _               ____  _
#  / ___| | __ _ _ __   |  _ \| |_   _ ___
# | |   | |/ _` | '_ \  | |_) | | | | / __|
# | |___| | (_| | | | | |  __/| | |_| \__ \
#  \____|_|\__,_|_| |_| |_|   |_|\__,_|___/
#
# A plugin made by Cortez_Romeo (Discord: https://discord.gg/NWbTVddmBM)
#
#  Notes:
#  * Supports hex color
#  * There are 3 main types:
#    + material: set the value to the MATERIAL of the block
#      > For Minecraft versions below 1.13, you can use a number in 'value:' and 'data:'
#          Example: (value: 95 | data: 1) [https://minecraft-ids.grahamedgecombe.com/]
#      > For versions above 1.12.2, you can directly enter the item name (the 'data:' field is no longer needed)
#          Example: (value: BOOK) [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html]
#    + playerhead: used for the "bet-player:" item to display a player's head
#    + customhead: see the section below
#      + How to use custom-head:
#          Step 1: Go to a custom head you want at https://minecraft-heads.com/custom-heads/
#          Step 2: Scroll to the bottom and find the "Other" section, copy the "Value:" field and
#                  paste it into the "value:" field of the item you want

title: '&0Clan Settings'
rows: 4
items:
  border:
    enabled: true
    name: ''
    type: material
    value: BLACK_STAINED_GLASS_PANE
    customModelData: 0
    click-sound:
      enabled: false
      name: ''
      volume: 1
      pitch: 1
    lore:
      - ''
  close:
    name: '&cClose'
    slot: 31
    type: customhead
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ==
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - '&eClick here to close'
  back:
    name: '&eGo Back'
    slot: 30
    type: customhead
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDliMmJlZTM5YjZlZjQ3ZTE4MmQ2ZjFkY2E5ZGVhODQyZmNkNjhiZGE5YmFjYzZhNmQ2NmE4ZGNkZjNlYyJ9fX0=
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - '&eClick here to go back'
  setIcon:
    name: '&eCustomize Clan Icon'
    slot: 10
    type: material
    value: item_frame
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - ''
      - '&fClan icon can be customized using'
      - '&f&eMATERIAL&f or &eCUSTOM HEAD&f.'
      - ''
      - '&fUses &cminecraft-heads.com&f for custom head data.'
      - ''
      - '&eClick here to customize'
  setCustomName:
    name: '&eCustomize Custom Name'
    slot: 11
    type: material
    value: name_tag
    customModelData: 0
    click-sound:
      enabled: true
      name: 'UI_CARTOGRAPHY_TABLE_TAKE_RESULT'
      volume: 1
      pitch: 1
    lore:
      - ''
      - '&fThe custom name is a subtitle that can include'
      - '&fcolors, special characters, and spaces.'
      - ''
      - '%checkPermission%'
    placeholders:
      checkPermission:
        true: '&eClick here to apply'
        false: '&cYou must be %getRequiredRank%&c to perform this.'
  setMessage:
    name: '&eCustomize Message'
    slot: 12
    type: material
    value: flower_banner_pattern
    customModelData: 0
    click-sound:
      enabled: true
      name: 'UI_CARTOGRAPHY_TABLE_TAKE_RESULT'
      volume: 1
      pitch: 1
    lore:
      - ''
      - '&fThe clan message shows when a member logs in'
      - '&for when using commands or interfaces.'
      - ''
      - '&fIt can be used for announcements or updates.'
      - ''
      - '%checkPermission%'
    placeholders:
      checkPermission:
        true: '&eClick here to apply'
        false: '&cYou must be %getRequiredRank%&c to perform this.'
  setSpawn:
    name: '&eSet Clan Spawn'
    slot: 13
    type: material
    value: red_bed
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - ''
      - '&fClan spawn is a teleport point for members.'
      - ''
      - '%checkPermission%'
    placeholders:
      checkPermission:
        true: '&eClick here to set spawn at your current location'
        false: '&cYou must be %getRequiredRank%&c to perform this.'
  setPermission:
    name: '&eConfigure Permissions'
    slot: 14
    type: material
    value: totem_of_undying
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - ''
      - '&fConfigure rank permissions for your clan.'
      - ''
      - '&fInvite Members: %invite_rank%'
      - '&fKick Members: %kick_rank%'
      - '&fCustom Name: %setcustomname_rank%'
      - '&fIcon: %seticon_rank%'
      - '&fTeleport to Spawn: %spawn_rank%'
      - '&fSet Spawn Point: %setspawn_rank%'
      - '&fCustom Message: %setmessage_rank%'
      - '&fAdd Manager: %setmanager_rank%'
      - '&fRemove Manager: %removemanager_rank%'
      - '&fUse Clan Chat: %chat_rank%'
      - '&fUpgrade: %upgrade_rank%'
      - '&fManage Allies: %manageally_rank%'
      - ''
      - '%checkPermission%'
    placeholders:
      checkPermission:
        true: '&eClick here to configure'
        false: '&cYou must be %getRequiredRank%&c to perform this.'
  setDiscord:
    name: '&eSet Discord'
    slot: 15
    type: customhead
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzM5ZWU3MTU0OTc5YjNmODc3MzVhMWM4YWMwODc4MTRiNzkyOGQwNTc2YTI2OTViYTAxZWQ2MTYzMTk0MjA0NSJ9fX0=
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - ''
      - '&fUse Discord for clan announcements'
      - '&for syncing clan chat to a Discord channel.'
      - ''
      - '%checkPermission%'
    placeholders:
      checkPermission:
        true: '&eClick here to configure'
        false: '&cYou must be %getRequiredRank%&c to perform this.'
  disband:
    name: '&eDisband Clan'
    slot: 16
    type: customhead
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmUwZmQxMDE5OWU4ZTRmY2RhYmNhZTRmODVjODU5MTgxMjdhN2M1NTUzYWQyMzVmMDFjNTZkMThiYjk0NzBkMyJ9fX0=
    customModelData: 0
    click-sound:
      enabled: true
      name: 'BLOCK_STONE_BUTTON_CLICK_ON'
      volume: 1
      pitch: 2
    lore:
      - ''
      - '&fDisbanding will delete all clan data, including'
      - '&fupgrades, members, and all related content.'
      - '&fThis action is irreversible.'
      - ''
      - '%checkPermission%'
    placeholders:
      checkPermission:
        true: '&eClick here to confirm'
        false: '&cYou must be %getRequiredRank%&c to perform this.'