#
#    ____ _               ____  _
#  / ___| | __ _ _ __   |  _ \| |_   _ ___
# | |   | |/ _` | '_ \  | |_) | | | | / __|
# | |___| | (_| | | | | |  __/| | |_| \__ \
#  \____|_|\__,_|_| |_| |_|   |_|\__,_|___/
#
# A plugin made by Cortez_Romeo (Discord: https://discord.gg/NWbTVddmBM)

# Đặt license key đã mua tại dihoastore.net tại đây (Hướng dẫn cài: https://bit.ly/3gJtsbp)
license-key: "XXXX-XXXX-XXXX-XXXX"

# Dành cho việc fix lỗi, không cần bật nếu không cần đến.
debug:
  enabled: false
  prefix: '&e[CLAN+ DEBUG] '

# Ngôn ngữ nào sẽ được sử dụng để hiển thị thông báo
# Bao gồm: vi (Tiếng Việt)
language: vi

# Cơ sỡ dữ liệu nào nên được sử dụng để xử lý các dữ liệu.
# Vui lòng restart lại máy chủ sau khi thay đổi các giá trị dưới đây.
database:
  # Bao gồm: YAML, H2
  # Khuyến khích sử dụng cơ sỡ dữ liệu H2.
  type: YAML
  # Khi smart-loading được bật, các dữ liệu người chơi được load khi khởi động máy chủ sẽ chỉ load những người ở trong clan.
  # Như đã nêu ở trên, việc không load các dữ liệu người chơi không ở trong clan sẽ giúp tiết kiệm rất nhiều thời gian.
  smart-loading:
    enabled: true
  # Các phiên bản cũ có thể gây ra lỗi dữ liệu như có các bang hội mà chủ bang hội không ở trong bang thành ra bang hội đó chết.
  # Nếu bật tính năng này thì khi đang load plugin, hệ thống sẽ tự động xóa các dữ liệu không hợp lệ.
  fix-bug-database:
    enabled: true
  # Tự động lưu dữ liệu.
  auto-save:
    enabled: true
    # Tự động lưu mỗi ... giây.
    seconds: 900
  # Thiết lập cơ sỡ dữ liệu
  settings:
    h2:
      file-name: 'h2Database'
      table:
        clan: 'clandata'
        player: 'playerdata'

# Tùy chỉnh các thông số mặc định.
clan-settings:
  # Số tiền cần để tạo.
  creating-clan-settings:
    # Số tiền tệ cần để tạo bang hội
    # PLAYERPOINTS
    # VAULT
    currency-requirement:
      type: VAULT
      value: 1000
    # Số lượng thành viên tối đa mặc định
    maximum-member-default: 5
    # Icon bang hội mặc định khi vừa tạo bang
    icon-default:
      type: MATERIAL
      value: DIRT
    # ID Skill: Level mặc định
    # Có thể thêm hoặc bớt
    skill-level-default:
      1: 0
      2: 0
      3: 0
      4: 0
    # Các quyền mặc định sẽ được thiết lập cho clan khi vừa tạo.
    # Clan sẽ có quyền tùy chỉnh cái quyền dưới đây.
    # Các rank bao gồm: LEADER, MANAGER, MEMBER.
    # Lưu ý: LEADER > MANAGER > MEMBER - Nếu quyền đó member xài được thì manager và leader xài được, nếu quyền đó manager xài được thì leader xài được.
    permission-default:
      INVITE: MANAGER
      KICK: MANAGER
      SETCUSTOMNAME: LEADER
      SETICON: LEADER
      SPAWN: MEMBER
      SETSPAWN: LEADER
      SETMESSAGE: LEADER
      SETMANAGER: LEADER
      REMOVEMANAGER: LEADER
      CHAT: MEMBER
      UPGRADE: MEMBER
      MANAGEALLY: MANAGER

  # Nếu tùy chọn này được bật,
  use-default-permission: false

  # Thiết lập về mời người chơi vào bang hội
  invite-settings:
    # Thời gian cần để chấp nhận.
    time-to-accept: 30

  # Thiết lập về tùy chỉnh tên bang hội
  clan-name-settings:
    # Cấm đặt các tên sau (Bao gồm tên bang hội và tên custom).
    prohibited-name:
    - admin
    - staff
    - helper
    - moderator
    - administrator
    - staffs
    - admins
    - moderators
    - administrators
    - helpers
    - owner
    - owners
    # Ký tự cấm (& vẫn xài được để đặt tên custom cho bang hội).
    prohibited-character:
    - '&'
    # Số ký tự tối thiểu có thể đặt cho tên bang hội (Không tính mã màu).
    minimum-length: 3
    # Số ký tự tối đa có thể đặt cho tên tên bang hội (Không tính mã màu).
    maximum-length: 20

# Những plugin có thể dùng để hỗ trợ plugin BangHoi.
# Bao gồm: PlaceholderAPI, DiscordSRV.
soft-depends:
  placeholderapi:
    clanless: '&c<Không có bang hội>'
    clan-top: '&#d1d1d1#%number% &r%name% &e&l━ &#f25eff%value% Điểm'

# Bstats dùng để thống kê số liệu mấy chủ và số người chơi sử dụng plugin.
# Không ảnh hướng đến hiệu năng của máy chủ.
bStats:
  enabled: true