#
#    ____ _               ____  _
#  / ___| | __ _ _ __   |  _ \| |_   _ ___
# | |   | |/ _` | '_ \  | |_) | | | | / __|
# | |___| | (_| | | | | |  __/| | |_| \__ \
#  \____|_|\__,_|_| |_| |_|   |_|\__,_|___/
#
# A plugin made by Cortez_Romeo (Discord: https://discord.gg/NWbTVddmBM)

# For debugging purposes, don’t enable unless necessary.
debug:
  enabled: false
  prefix: '&e[CLAN+ DEBUG] '

# Language to be used for displaying messages.
# Options:
# en (English)
# vi (Vietnamese)
language: en

# Which database should be used to handle data.
# Please restart the server after changing the values below.
database:
  # Options: YAML, H2
  # Recommended to use H2 database.
  type: YAML
  # When smart-loading is enabled, only data of players in clans will be loaded at server startup.
  # As mentioned above, not loading data for non-clan players can save a lot of time.
  smart-loading:
    enabled: true
  # Older versions might cause data issues such as having clans without a leader.
  # If this option is enabled, the system will automatically remove invalid data while loading the plugin.
  fix-bug-database:
    enabled: true
  # Automatically save data.
  auto-save:
    enabled: true
    # Auto-save every ... seconds.
    seconds: 900
  # Backup options
  backup-settings:
    # https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    file-name-date-format: 'HH-mm-ss MM-dd-yyyy'

  # Database setup.
  settings:
    h2:
      file-name: 'h2Database'
      table:
        clan: 'clandata'
        player: 'playerdata'

# Progress bar.
progress-bar:
  # Total number of bars.
  total-bars: 20
  symbol:
    # Completed bar.
    completed: '&2&m━'
    # Not completed bar.
    not-completed: '&f&m━'

# Default configuration settings.
clan-settings:
  # Cost to create a clan.
  creating-clan-settings:
    # Currency required to create a clan.
    # PLAYERPOINTS
    # VAULT
    currency-requirement:
      enabled: true
      type: VAULT
      value: 1000
    # Default maximum number of members.
    maximum-member-default: 5
    # Default clan icon upon creation.
    icon-default:
      type: MATERIAL
      value: ITEM_FRAME
    # Default skill levels by skill ID.
    # You can add or remove entries.
    skill-level-default:
      1: 0
      2: 0
      3: 0
      4: 0
    # Default permissions set for newly created clans.
    # Clan can modify the permissions listed below.
    # Ranks include: LEADER, MANAGER, MEMBER
    # Note: LEADER > MANAGER > MEMBER — if MEMBER has a permission, MANAGER and LEADER also have it; if MANAGER has it, LEADER also has it.
    permission-default:
      INVITE: MANAGER
      KICK: MANAGER
      SETCUSTOMNAME: LEADER
      SETICON: LEADER
      SPAWN: MEMBER
      SETSPAWN: LEADER
      SETMESSAGE: LEADER
      SETMANAGER: LEADER
      REMOVEMANAGER: LEADER
      CHAT: MEMBER
      UPGRADE: MANAGER
      MANAGEALLY: MANAGER
      OPENSTORAGE: MEMBER
    # Default available storage for newly created clans.
    # Player will need to upgrade their max storage number to use more inventories.
    # Set to 0 to not give any available storages to new clans.
    max-storage-default: 1

    # Send a broadcast to all the players in the server about the creation of a new clan.
    # The plugin will select a random message from one of those lines below, set to 1 line to only use 1.
    # Or just leave a single line like - '' to disable
    creation-broadcast:
      - '&#3498eb&lNEW CLAN&r &#35d11d&l| &e%player% &fjust created a new clan named &b%clanName%&f.'
      - '&#3498eb&lNEW CLAN&r &#35d11d&l| &b%clanName% &fjust got created by &e%player%&f.'

  # If this option is enabled, permissions of all clans on the server will be set
  # to the defaults in "permission-default" above, and no clan will be able to change
  # their permissions unless this is disabled.
  permission-default-forced: false

  # Settings for set spawn
  set-spawn-settings:
    blacklist-worlds:
      enabled: true
      # If player is in on of these words, they will not be able to set spawn.
      worlds:
        - blacklistworld1
        - blacklistworld2

  # Settings for clan spawn
  spawn-settings:
    enabled: true
    countdown:
      enabled: true
      seconds: 5

  # Settings for inviting players to the clan.
  invite-settings:
    # Time allowed to accept the invite.
    time-to-accept: 30

  # Settings for adjusting the delaying of sending messages
  messages-settings:
    on-join:
      # Using to send the status of current war event
      war-event:
        enabled: true
        # Delay for ... seconds
        delay: 1
      # Using to send the player's clan broadcast
      clan-broadcast:
        enabled: true
        # Delay for ... seconds
        delay: 2

  # Settings for customizing clan name.
  clan-name-settings:
    # Prohibited names (applies to both clan and custom names).
    prohibited-name:
      - admin
      - staff
      - helper
      - moderator
      - administrator
      - staffs
      - admins
      - moderators
      - administrators
      - helpers
      - owner
      - owners
    # Prohibited characters (Note: & is still allowed for custom names).
    prohibited-character:
      - '&'
    # Minimum character length for clan name (excluding color codes).
    minimum-length:
      clan-name: 3
      clan-custom-name: 3
    # Maximum character length for clan name (excluding color codes).
    maximum-length:
      clan-name: 20
      clan-custom-name: 30

# Chat settings
chat-settings:
  # Some chat plugins have not supported paper async chat yet so it will cause a problem that will make
  # clansplus still sends players' messages even if they are using clans chat or any chat related features.
  use-paper-async-chat: false
  # Use the word below to cancel chat interaction.
  stop-using-chat-word: '?cancel'

# Sign-input settings
sign-input-settings:
  # Close player's sign using to serach after the time runs out.
  time-out: 15

# Vanish settings
# Supports SuperVanish, PremiumVanish, EssentialsX, VanishNoPacket, and other vanish-supporting plugins
vanish-settings:
  # Whether to show vanished players in GUI
  # Vanished players will appear as OFFLINE
  hide-vanish-player:
    enabled: true

# Storage settings
# Modify max storage number or other stuffs related to clan storage here.
storage-settings:
  enabled: true
  # Changing this after player already created and put items in clan storage might cause losing items!
  slots: 54
  # Max storage for player to upgrade or utilize.
  # Any storage numbers exceed the number below won't be able to use or upgrade.
  max-storage: 30

# Plugins that can support the Clan plugin.
# Includes: PlaceholderAPI.
soft-depends:
  placeholderapi:
    # Returns "no-clan" if the player is not in a clan
    no-clan: 'N/A'
    # %value% is the value that placeholder returns
    placeholders:
      # Clan placeholders
      clan_name: '%value%'
      clan_customname: '%value%'
      clan_formatname: '%value%'
      clan_owner: '%value%'
      clan_message: '%value%'
      clan_score: '%value%'
      clan_warpoint: '%value%'
      clan_warning: '%value%'
      clan_maxmembers: '%value%'
      clan_createddate: '%value%'
      clan_format_createddate: '%value%'
      clan_members: '%value%'
      clan_allies: '%value%'
      clan_skilllevel_: '%value%'
      clan_subjectpermission_: '%value%'
      clan_format_subjectpermission_: '%value%'
      clan_discordchannelid: '%value%'
      clan_discordjoinlink: '%value%'
      # Player placeholders
      player_rank: '%value%'
      player_format_rank: '%value%'
      player_joindate: '%value%'
      player_format_joindate: '%value%'
      player_scorecollected: '%value%'
      player_lastactivated: '%value%'
      player_format_lastactivated: '%value%'
      # Top placeholders
      # %formatClanName%: Gets the display name of the clan, or original name if none
      # %clanName%: Gets the original clan name
      # %top%: Gets the top number
      top_score_name_: '&r%formatClanName%'
      top_score_value_: '%value%'
  # Put your discord web hook here to let plugin send plugin messages to your discord channel
  discordWebhook:
    webhookURL: ""