#
#    ____ _               ____  _
#  / ___| | __ _ _ __   |  _ \| |_   _ ___
# | |   | |/ _` | '_ \  | |_) | | | | / __|
# | |___| | (_| | | | | |  __/| | |_| \__ \
#  \____|_|\__,_|_| |_| |_|   |_|\__,_|___/
#
# A plugin made by Cortez_Romeo (Discord: https://discord.gg/NWbTVddmBM)

# For debugging purposes, don’t enable unless necessary.
debug:
  enabled: false
  prefix: '&e[CLAN+ DEBUG] '

# Language to be used for displaying messages.
# Options:
# en (English)
# vi (Vietnamese)
language: en

# Which database should be used to handle data.
# Please restart the server after changing the values below.
database:
  # Options: YAML, H2
  # Recommended to use H2 database.
  type: YAML
  # When smart-loading is enabled, only data of players in clans will be loaded at server startup.
  # As mentioned above, not loading data for non-clan players can save a lot of time.
  smart-loading:
    enabled: true
  # Older versions might cause data issues such as having clans without a leader.
  # If this option is enabled, the system will automatically remove invalid data while loading the plugin.
  fix-bug-database:
    enabled: true
  # Automatically save data.
  auto-save:
    enabled: true
    # Auto-save every ... seconds.
    seconds: 900
  # Backup options
  backup-settings:
    # https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    file-name-date-format: 'HH-mm-ss MM-dd-yyyy'

  # Database setup.
  settings:
    h2:
      file-name: 'h2Database'
      table:
        clan: 'clandata'
        player: 'playerdata'

# Progress bar.
progress-bar:
  # Total number of bars.
  total-bars: 20
  symbol:
    # Completed bar.
    completed: '&2&m━'
    # Not completed bar.
    not-completed: '&f&m━'

# Default configuration settings.
clan-settings:
  # Cost to create a clan.
  creating-clan-settings:
    # Currency required to create a clan.
    # PLAYERPOINTS
    # VAULT
    currency-requirement:
      enabled: true
      type: VAULT
      value: 1000
    # Default maximum number of members.
    maximum-member-default: 5
    # Default clan icon upon creation.
    icon-default:
      type: MATERIAL
      value: ITEM_FRAME
    # Default skill levels by skill ID.
    # You can add or remove entries.
    skill-level-default:
      1: 0
      2: 0
      3: 0
      4: 0
    # Default permissions set for newly created clans.
    # Clan can modify the permissions listed below.
    # Ranks include: LEADER, MANAGER, MEMBER
    # Note: LEADER > MANAGER > MEMBER — if MEMBER has a permission, MANAGER and LEADER also have it; if MANAGER has it, LEADER also has it.
    permission-default:
      INVITE: MANAGER
      KICK: MANAGER
      SETCUSTOMNAME: LEADER
      SETICON: LEADER
      SPAWN: MEMBER
      SETSPAWN: LEADER
      SETMESSAGE: LEADER
      SETMANAGER: LEADER
      REMOVEMANAGER: LEADER
      CHAT: MEMBER
      UPGRADE: MANAGER
      MANAGEALLY: MANAGER

  # If this option is enabled, permissions of all clans on the server will be set
  # to the defaults in "permission-default" above, and no clan will be able to change
  # their permissions unless this is disabled.
  permission-default-forced: false

  set-spawn-settings:
    blacklist-worlds:
      enabled: true
      worlds:
        - blacklistworld1
        - blacklistworld2

  # Delay time before teleporting to clan spawn.
  spawn-countdown:
    enabled: true
    seconds: 5

  # Settings for inviting players to the clan.
  invite-settings:
    # Time allowed to accept the invite.
    time-to-accept: 30

  # Settings for adjusting the delaying of sending messages
  messages-settings:
    on-join:
      # Using to send the status of current war event
      war-event:
        enabled: true
        # Delay for ... seconds
        delay: 1
      # Using to send the player's clan broadcast
      clan-broadcast:
        enabled: true
        # Delay for ... seconds
        delay: 2

  # Settings for customizing clan name.
  clan-name-settings:
    # Prohibited names (applies to both clan and custom names).
    prohibited-name:
      - admin
      - staff
      - helper
      - moderator
      - administrator
      - staffs
      - admins
      - moderators
      - administrators
      - helpers
      - owner
      - owners
    # Prohibited characters (Note: & is still allowed for custom names).
    prohibited-character:
      - '&'
    # Minimum character length for clan name (excluding color codes).
    minimum-length:
      clan-name: 3
      clan-custom-name: 3
    # Maximum character length for clan name (excluding color codes).
    maximum-length:
      clan-name: 20
      clan-custom-name: 30

# Chat settings
chat-settings:
  # Use the word below to cancel chat interaction.
  stop-using-chat-word: '?cancel'

# Sign-input settings
sign-input-settings:
  # Close player's sign using to serach after the time runs out.
  time-out: 15

# Vanish settings
# Supports SuperVanish, PremiumVanish, EssentialsX, VanishNoPacket, and other vanish-supporting plugins
vanish-settings:
  # Whether to show vanished players in GUI
  # Vanished players will appear as OFFLINE
  hide-vanish-player:
    enabled: true

# Plugins that can support the Clan plugin.
# Includes: PlaceholderAPI.
soft-depends:
  placeholderapi:
    # Returns "no-clan" if the player is not in a clan
    no-clan: 'N/A'
    # %formatClanName%: Gets the display name of the clan, or original name if none
    # %clanName%: Gets the original clan name
    # %top%: Gets the top number
    top-score-name: '&r%formatClanName%'
    top-score-value: '%value%'
  discordWebhook:
    webhookURL: ""